---
title: "2_Alpha_and_betaDiv"
author: "Lola"
date: "7/3/2023"
output: html_document
---
He observado que tienen un control negativo y un blanco (FRC_Blanco y CN?) si me explicáis lo que es se puede hacer un filtrado de contaminación con el paquete decontam() si no lo ha hecho ya FISABIO 
```{r Libraries}
library(phyloseq)
library(microbiome)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(data.table)
library(knitr)
library(grid)
library(gridExtra)
```


```{r cargamos datos}
ps <- readRDS("OneDrive - Universitat de Valencia/Doctorado/Estudios/IATA/Rotura_de_cadera/output/ps.Rds")
otu<-as.data.frame(otu_table(ps))

```

```{r Counts}
reads_per_sample <- as.matrix(rowSums(t(otu)))
# Remove samples with less than MINREADS from phyloseq object
#ps <- prune_taxa(taxa_sums(ps) > 0, ps)
# merge all taxa that are detected rare
#total_samples <- phyloseq::nsamples(ps)
#ps
#saveRDS(ps, "~/Documents/Lola/CIPF_2018/Rats_HE_CCL4model/output/ps.Rds")
```
No hacemos lo anterior proque parece que ya lo han hecho...preguntar a Gaspar si son los datos crudos o si ya se habían eliminado los ceros

# ASV level Group
```{r Alpha Diversity}
metadata<-data.frame(sample_data(ps))
metadata$Group <- metadata$Fractura.Caso.Control.Control
metadata <- metadata %>%
    mutate(Group = case_when(
        Group == "Control" ~ "Control",
        Group == "Fractura" ~ "Hip Fracture",
        TRUE ~ NA_character_ # Default case
    ))

sample_data(ps)<-metadata

newSTorder = c("Control", "Hip Fracture")
my_comparisons <- list(c("Control", "Hip Fracture"))
library(ggsignif)
library(ggpubr)

#Shannon
pShannon <- plot_richness(ps, x="Group", measures=c("Shannon")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("Shannon")
#Re-arranging the order of the figure, controls first
pShannon$data$Group <- as.character(pShannon$data$Group)
pShannon$data$Group <- factor(pShannon$data$Group, levels=newSTorder)
pShannon$layers<-pShannon$layers[-1]
pShannon 


#Chao1
pChao <- plot_richness(ps, x="Group", measures=c("Chao1")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("Chao1")
#Re-arranging the order of the figure, controls first
pChao$data$Group <- as.character(pChao$data$Group)
pChao$data$Group <- factor(pChao$data$Group, levels=newSTorder)
pChao$layers<-pChao$layers[-1]
pChao 

#ACE
pACE <-  plot_richness(ps, x="Group", measures=c("ACE")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("ACE")
pACE$data$Group <- as.character(pACE$data$Group)
pACE$data$Group <- factor(pACE$data$Group, levels=newSTorder)
pACE$layers<-pACE$layers[-1]
pACE 
ggarrange(pChao,pACE,pShannon, common.legend = TRUE, legend="bottom",nrow = 1)
```

```{r Beta Diversity}
metadata<-as.data.frame(sample_data(ps))
metadata$Group <- ifelse(metadata$X0.Caso.1.Control == 0, "Caso", "Control")
sample_data(ps)<-metadata
#Beta Diversity
library(tibble)
library(ggplot2)
library(forcats)
#No transformations Bray distance
dist = phyloseq::distance(ps, method="bray")
ordination = ordinate(ps, method="PCoA", distance=dist)
plot_ordination(ps, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)

#Relative abundance Bray distance
ps_comp<- microbiome::transform(ps, "compositional")
dist = phyloseq::distance(ps_comp, method="bray")
ordination = ordinate(ps_comp, method="PCoA", distance=dist)
plot_ordination(ps_comp, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)

#Cntered-log-ratio transformation euclidean distance
ps_clr<- microbiome::transform(ps, "clr")

dist = phyloseq::distance(ps_clr, method="euclidean")
ordination = ordinate(ps_clr, method="PCoA", distance=dist)
plot_ordination(ps_clr, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)
```

# Genus level Group
```{r Alpha Diversity}
ps <- readRDS("~/OneDrive - Universitat de Valencia/Doctorado/Estudios/IATA/Rotura_de_cadera/output/ps.Rds")
metadata<-data.frame(sample_data(ps))
ps <- tax_glom(ps, taxrank = 'Genus', NArm = FALSE)
metadata$Group <- metadata$Fractura.Caso.Control.Control
metadata <- metadata %>%
    mutate(Group = case_when(
        Group == "Control" ~ "Control",
        Group == "Fractura" ~ "Hip Fracture",
        TRUE ~ NA_character_ # Default case
    ))

sample_data(ps)<-metadata
ps_genus <- tax_glom(ps, taxrank = 'Genus', NArm = FALSE)
newSTorder = c("Control", "Hip Fracture")
my_comparisons <- list(c("Control", "Hip Fracture"))
library(ggsignif)
library(ggpubr)

#Shannon
pShannon <- plot_richness(ps_genus, x="Group", measures=c("Shannon")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("Shannon")
#Re-arranging the order of the figure, controls first
pShannon$data$Group <- as.character(pShannon$data$Group)
pShannon$data$Group <- factor(pShannon$data$Group, levels=newSTorder)
pShannon$layers<-pShannon$layers[-1]
pShannon 


#Chao1
pChao <- plot_richness(ps_genus, x="Group", measures=c("Chao1")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("Chao1")
#Re-arranging the order of the figure, controls first
pChao$data$Group <- as.character(pChao$data$Group)
pChao$data$Group <- factor(pChao$data$Group, levels=newSTorder)
pChao$layers<-pChao$layers[-1]
pChao 

#ACE
pACE <-  plot_richness(ps_genus, x="Group", measures=c("ACE")) +
    geom_violin(aes(color = Group), trim = FALSE) +  
   geom_boxplot(width = 0.2) +
  theme_classic() + theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90), axis.text.x = element_text(size = 12)) +
    stat_compare_means(label= "p.signif", comparisons = my_comparisons, method = "t.test")+
    ylab("ACE")
pACE$data$Group <- as.character(pACE$data$Group)
pACE$data$Group <- factor(pACE$data$Group, levels=newSTorder)
pACE$layers<-pACE$layers[-1]
pACE 
ggarrange(pChao,pACE,pShannon, common.legend = TRUE, legend="bottom",nrow = 1)
```

```{r Beta Diversity}
metadata<-as.data.frame(sample_data(ps))
metadata$Group <- ifelse(metadata$X0.Caso.1.Control == 0, "Caso", "Control")
sample_data(ps)<-metadata
#Beta Diversity
library(tibble)
library(ggplot2)
library(forcats)
#No transformations Bray distance
dist = phyloseq::distance(ps, method="bray")
ordination = ordinate(ps, method="PCoA", distance=dist)
plot_ordination(ps, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)

#Relative abundance Bray distance
ps_comp<- microbiome::transform(ps, "compositional")
dist = phyloseq::distance(ps_comp, method="bray")
ordination = ordinate(ps_comp, method="PCoA", distance=dist)
plot_ordination(ps_comp, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)

#Cntered-log-ratio transformation euclidean distance
ps_clr<- microbiome::transform(ps, "clr")

dist = phyloseq::distance(ps_clr, method="euclidean")
ordination = ordinate(ps_clr, method="PCoA", distance=dist)
plot_ordination(ps_clr, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)
```